services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - zipkin

  orquestrador-clima:
    build:
      context: ./orquestrador-clima
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - otel-collector

  servico-a:
    build:
      context: ./validador-cep
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - URL_API_TEMPERATURA=http://orquestrador-clima:8081
    depends_on:
      - otel-collector